#!/bin/bash
sudo su -
yum update -y
yum install git -y
yum install maven -y
yum install java-17 -y
yum install docker -y
systemctl start docker
systemctl enable docker
docker run -d -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts



To remove all images at one shot
docker image prune -a -y
To remove all containers at one shot
docker system prune -a -y
To remove all the volumes at one shot
docker volume prune 
